-- MySQL Script generated by MySQL Workbench
-- qui 09 jun 2022 22:38:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adopet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adopet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adopet` DEFAULT CHARACTER SET utf8 ;
USE `adopet` ;

-- -----------------------------------------------------
-- Table `states`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `states` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cities` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `state_id` INT NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_cities_states_idx` (`state_id` ASC) ,
    CONSTRAINT `fk_cities_states`
    FOREIGN KEY (`state_id`)
    REFERENCES `states` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `city_id` INT NOT NULL,
    `state_id` INT NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(20) NULL,
    `description` TEXT NULL,
    `password` TEXT NOT NULL,
    `photo` TEXT NULL,
    `type` ENUM('normal', 'moderator') NOT NULL,
    `show_email` TINYINT NOT NULL,
    `show_phone` TINYINT NOT NULL,
    `show_address` TINYINT NOT NULL,
    `address` VARCHAR(100) NOT NULL,
    `number` SMALLINT NULL,
    `zip_code` CHAR(9) NOT NULL,
    `complement` VARCHAR(45) NULL,
    `total_pets` TINYINT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` VARCHAR(45) NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
    INDEX `fk_users_cities1_idx` (`city_id` ASC) ,
    INDEX `fk_users_states1_idx` (`state_id` ASC) ,
    CONSTRAINT `fk_users_cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `cities` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_users_states1`
    FOREIGN KEY (`state_id`)
    REFERENCES `states` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `breeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `breeds` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `animal_id` INT NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_breeds_animals1_idx` (`animal_id` ASC) ,
    CONSTRAINT `fk_breeds_animals1`
    FOREIGN KEY (`animal_id`)
    REFERENCES `animals` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pets` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `breed_id` INT NOT NULL,
    `animal_id` INT NOT NULL,
    `name` VARCHAR(45) NOT NULL,
    `description` TEXT NOT NULL,
    `gender` ENUM('female', 'male') NOT NULL,
    `age` TINYINT NOT NULL,
    `weight` TINYINT NOT NULL,
    `size` ENUM('mini', 'small', 'medium', 'big', 'giant') NOT NULL,
    `castrated` TINYINT NOT NULL,
    `vaccinated` TINYINT NOT NULL,
    `wormed` TINYINT NOT NULL,
    `special` VARCHAR(45) NULL,
    `exams` VARCHAR(255) NULL,
    `status` ENUM('active', 'analysis', 'standy_by', 'inactive') NOT NULL DEFAULT 'analysis',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_pets_users1_idx` (`user_id` ASC) ,
    INDEX `fk_pets_breeds1_idx` (`breed_id` ASC) ,
    INDEX `fk_pets_animals1_idx` (`animal_id` ASC) ,
    CONSTRAINT `fk_pets_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `users` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_pets_breeds1` FOREIGN KEY (`breed_id`)
    REFERENCES `breeds` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_pets_animals1` FOREIGN KEY (`animal_id`)
    REFERENCES `animals` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `photo` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `pet_id` INT NOT NULL,
    `name` TEXT NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_photo_pets1_idx` (`pet_id` ASC) ,
    CONSTRAINT `fk_photo_pets1` FOREIGN KEY (`pet_id`) REFERENCES `pets` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
    ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
