-- name: create
INSERT INTO users (city_id,
                   state_id,
                   name,
                   email,
                   phone,
                   description,
                   password,
                   photo,
                   type,
                   show_email,
                   show_phone,
                   show_address,
                   address,
                   number,
                   zip_code,
                   complement,
                   total_pets)
VALUES (:city_id,
        :state_id,
        :name,
        :email,
        :phone,
        :description,
        :password,
        :photo,
        :type,
        :show_email,
        :show_phone,
        :show_address,
        :address,
        :number,
        :zip_code,
        :complement,
        :total_pets);